config/routes.rb
Rails.application.routes.draw do # rubocop:disable Style/FrozenStringLiteralComment
  # This will connect users to the devise auth
  devise_for :users, controllers: { registrations: 'users/registrations' }

  # This defines the response for GET "/" and routes to home controller's "index" method
  root 'entry#index'

  resources :projects

  get 'home', to: 'home#index'

  namespace :admin do
    resources :users, only: %i[index show update]
  end
  #
  #
  #
  #
  #
  #
  #
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/ability.rb
# frozen_string_literal: true

class Ability # rubocop:disable Style/Documentation
  include CanCan::Ability

  def initialize(user)
    # user ||= User.new # Omitted because mandatory authentication

    if user.admin?
      can :manage, Project
      can :manage, UserProject # Assuming you have a join model for users and projects
    else
      can :read, Project
      can :read, UserProject
      # Add more specific permissions as needed
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 20 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord # rubocop:disable Style/Documentation
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable

  enum role: %i[user admin]
  after_initialize :set_default_role, if: :new_record?
  def set_default_role
    self.role ||= :user
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def show
    @users = User.all
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(permitted_params)
      redirect_to '/admin/users'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def authenticate_admin!
    redirect_to root_path, alert: 'Access Denied' unless current_user.admin?
  end

  def permitted_params
    params.require(:user).permit(:email, :role)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entry_controller.rb
class EntryController < ApplicationController # rubocop:disable Style/Documentation,Style/FrozenStringLiteralComment
  def index # rubocop:disable Metrics/MethodLength
    @honbu_ascii = '⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡏⠙⠛⠛⠛⣛⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠙⠛⠛⠛⣛⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
    ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠛⠿⣿
    ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⣿
    ⣿⣿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠇⠀⠀⠀⠀⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⣿⣿ ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⠀⠀⠀⠀⣶⣶⣶⠆⠀⠀⠀⢰⣿⣿
    ⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⠉⠉⠀⢹⣿⣿⣿⣿⡇⠀⠀⠉⣹⣿⣿⣿⠀⠀⠀⠀⣿⣿⡟⠀⠀⠀⢠⣿⣿⣿
    ⣿⣿⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣿⣿⣿⣿⡇⠀⠀⠀⢿⣿⣿⡿⠁⠀⠀⢰⣿⣿⣿⣿⠀⠀⠀⠀⣿⣿⠁⠀⠀⠀⣾⣿⣿⣿
    ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠿⠿⠿⠀⠠⠤⠼⠿⠿⠇⠀⠀⠠⠿⠿⠿⠿⣿⠀⠀⠀⠀⣿⠃⠀⠀⠀⣼⣿⣿⣿⣿
    ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⠀⠀⠀⠀⣯⡀⠀⠀⠀⠻⣿⣿⣿⣿
    ⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⠀⠀⠀⢀⡇⠀⠀⠀⠀⣷⠀⠀⠀⠀⠈⣿⣿⣿⣿⣿⣿⣿⣿⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣿⠀⠀⠀⠀⣿⣿⡆⠀⠀⠀⠈⣿⣿⣿
    ⣿⣿⣿⣿⣿⣿⣿⠏⠀⠀⠀⠀⣠⣿⡇⠀⠀⠀⠀⣿⣷⡀⠀⠀⠀⠈⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⣿⣿⣿⣦⠀⠀⠀⠘⢿⣿
    ⣿⣿⣿⣿⣿⠟⠁⠀⠀⠀⢀⣴⣿⣿⡇⠀⠀⠀⠀⣿⣿⣿⣄⠀⠀⠀⠀⠈⠻⢿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⠀⠀⠀⠀⣿⣿⣿⣿⣇⠀⠀⠀⠸⣿
    ⣿⣿⡿⠋⠀⠀⠀⠀⠀⠠⠛⠛⠛⠛⠃⠀⠀⠀⠀⠛⠛⠛⠛⠓⠀⠀⠀⠀⠀⠀⠙⠻⣿⣿⣿⠀⠀⠀⠀⣀⣀⣀⣀⣀⣀⠀⠀⠀⠀⣿⣿⣿⠀⠀⠀⠀⣿⣿⣿⣿⣿⠀⠀⠀⠀⣿
    ⣯⡁⠀⠀⠀⠀⢀⣠⣾⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣷⣄⠀⠀⠀⠀⠀⣠⣿⣿⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⣿⣿⣿⠀⠀⠀⠀⡟⠛⠛⠛⠃⠀⠀⠀⢰⣿
    ⣿⣿⣦⠀⣀⣴⣿⣿⣷⣀⣀⣀⣀⣀⡀⠀⠀⠀⠀⣀⣀⣀⣀⣀⣸⣿⣿⣷⣤⡀⢀⣾⣿⣿⣿⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⣿⣿⣿⠀⠀⠀⠀⣷⠀⠀⠀⠀⠀⠀⣠⣾⣿
    ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⠀⠀⠀⠀⣿⣦⣤⣤⣤⣴⣾⣿⣿⣿
    ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⣀⣀⣀⣀⣀⣀⠀⠀⠀⠀⣿⣿⣿⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
    ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣇⣀⣀⣀⣀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣀⣀⣀⣀⣿⣿⣿⣿⣿⣿⣤⣤⣤⣤⣿⣿⣿⣀⣀⣀⣠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController # rubocop:disable Style/Documentation
  before_action :authenticate_user!

  def index
    @projects = Project.all
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  def index
    @projects = Project.all
    @first = Project.order(:id).first
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
    @projects = Project.all
  end

  def create
    @projects = Project.all
    @project = Project.new(permitted_params)
    if @project.save
      redirect_to project_path(@project)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @projects = Project.all
    @project = Project.find(params[:id])
    if @project.update(permitted_params)
      redirect_to @project
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to home_path, status: :see_other
  end

  private

  def permitted_params
    params.require(:project).permit(:name, :description)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create # rubocop:disable Lint/UselessMethodDefinition
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update # rubocop:disable Lint/UselessMethodDefinition
    super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entry_helper.rb
module EntryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/users/index.html.haml
- content_for :titlename do
  << User Account List >>
- content_for :styles do
  = stylesheet_link_tag 'admin_users'

- content_for :center_window do
  .user-list-container
    %table
      %thead
        %tr
          %th Email
          %th Role
          <!-- Add other user attributes you want to display -->
      %tbody
        - @users.each do |user|
          %tr
            %td= link_to user.email, admin_user_path(user)
            %td= user.role
            <!-- Add other user attributes you want to display -->


- content_for :bb_a do
  = link_to 'BACK to Main', home_path

app/views/admin/users/show.html.haml
- content_for :titlename do
  User Account  >>
  = @user.email
- content_for :styles do
  = stylesheet_link_tag 'admin_users'

- content_for :center_window do
  = form_with model: @user, url: admin_user_path(@user), method: :patch, local: true do |form|
    %h3
      = @user.email
      > Role/Permissions:
      = @user.role
    = form.label :role, "Admin", value: "admin"
    = form.radio_button :role, "admin"
    %br
    = form.label :role, "User", value: "user"
    = form.radio_button :role, "user"
    - @user.errors.full_messages_for(:role).each do |message|
      %div= message
    %br
    = form.submit "Update Role", class: "btn btn-primary"

- content_for :bb_a do
  = link_to 'BACK to Users', admin_users_path
- content_for :bb_d do
  - if user_signed_in?
    = link_to 'Log Out', destroy_user_session_path, 'data-turbo-method': :delete

app/views/entry/index.html.haml
- content_for :styles do
  = stylesheet_link_tag 'entry_style'

- content_for :center_window do
  %body
    .splash
      .ascii-art
        = @honbu_ascii.html_safe
        %br
        %br
      .login-link
        = link_to 'Access Headquarters', home_path
%footer

app/views/home/index.html.haml
- content_for :styles do
  = stylesheet_link_tag 'home'

- content_for :center_window do
  %h2 HELLO #{current_user.first_name}
  %p.tut-text
    This is your #{current_user.role} dashboard.
    %ul
      %li You can click on "Projects" in the lefthand window to view / modify / delete them.
      %li You can edit the details of your account using the "EDIT User Profile" button below this window.
      %li Log out using the link below as well.
      %br
      - if current_user.admin?
        You have ADMIN access which also allows:
        %li Viewing a current list of users, and modifying thier permissions/role.

- content_for :left_window do
  .left-window-title
    %h2 PROJECTS
  %ul.projects
  - @projects.each do |project|
    %li=  link_to project.name, project_path(project)

- content_for :titlename do
  << HQ MAIN >>

- content_for :bb_a do
  = link_to 'New PROJECT', new_project_path

- content_for :bb_b do
  - if current_user.admin?
    = link_to 'VIEW Users', admin_users_path

- content_for :bb_c do
  - if user_signed_in?
    = link_to "EDIT User Profile", edit_user_registration_path

- content_for :bb_d do
  - if user_signed_in?
    = link_to 'Log Out', destroy_user_session_path, 'data-turbo-method': :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title 本部 HQ
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags

  %body
    = yield :styles
    .wrapper
      / Navigation above main content
      %h1 本部 HonbuHQ
      .topbar
        .top_nav_spacer
        %nav.top-nav
          .admin_display
            - if user_signed_in?
              %p(style="#{current_user.admin? ? 'visibility: visible;' : 'visibility: hidden;'}")
                #{current_user.role}
          .title_display
            - if user_signed_in?
              = yield :titlename
          .user_display
            - if user_signed_in?
              %p
                User:
                #{current_user.first_name} #{current_user.last_name}
        .top_nav_spacer
      / Main content area
      .main-content
        / Left column (20%)
        #left-window.left-column
          = yield :left_window
        / Center column (60%)
        #main-window.center-column
          = yield :center_window
        / Right column (20%)
        #right-window.right-column
          = yield :right_window
      / Navigation below main content
      %nav.bottom-nav
        #l_button.LR_buttons
          #bb_left
          = yield :bb_left
        .center-segments
          .bottom_button
            #bb_a
            = yield :bb_a
          .bottom_button
            #bb_b
            = yield :bb_b
          .bottom_button
            #bb_c
            = yield :bb_c
          .bottom_button
            #bb_d
            = yield :bb_d
        #r_button.LR_buttons
          #bb_right
          = yield :bb_right
  %footer

app/views/projects/edit.html.haml
- content_for :styles do
  = stylesheet_link_tag 'project'

- content_for :titlename do
  EDIT PROJECT:
  = @project.name

- content_for :left_window do
  %br
  %br

- content_for :center_window do
  = form_with model: @project do |form|
    Project
    = form.label :name
    = form.text_field :name
    - @project.errors.full_messages_for(:name).each do |message|
      %div= message
    %br
    %br
    = form.label :description, class: 'description-label'
    = form.text_area :description, rows: 15, cols: 80, class: 'description-text-area'
    - @project.errors.full_messages_for(:description).each do |message|
      %div= message
    %br
    = form.submit


- content_for :bb_a do
  = link_to 'BACK to Main', home_path
- content_for :bb_d do
  - if user_signed_in?
    = link_to 'Log Out', destroy_user_session_path, 'data-turbo-method': :delete

app/views/projects/index.html.haml
- content_for :styles do
  = stylesheet_link_tag 'project'

- content_for :titlename do
  PROJECT: #{@first.name}

- content_for :center_window do
  %h3
    Project Description
  = @first.description

- content_for :left_window do
  %ul.projects
  - @projects.each do |project|
    %li=  link_to project.name, project_path(project)
  %br
  %br
- content_for :bb_b do
  = link_to 'New Project', new_project_path

- content_for :bb_d do
  - if user_signed_in?
    = link_to 'Log Out', destroy_user_session_path, 'data-turbo-method': :delete

app/views/projects/new.html.haml
- content_for :styles do
  = stylesheet_link_tag 'project'

- content_for :titlename do
  << CREATE PROJECT >>

- content_for :left_window do
  %ul.projects
  - @projects.each do |project|
    %li=  link_to project.name, project_path(project)
  %br
  %br

- content_for :center_window do
  = form_with model: @project do |form|
    Project
    = form.label :name
    = form.text_field :name
    - @project.errors.full_messages_for(:name).each do |message|
      %div= message
    %br
    %br
    = form.label :description, class: 'description-label'
    = form.text_area :description, rows: 15, cols: 80, class: 'description-text-area'
    - @project.errors.full_messages_for(:description).each do |message|
      %div= message
    %br
    = form.submit


- content_for :bb_a do
  = link_to 'BACK to Main', home_path
- content_for :bb_d do
  - if user_signed_in?
    = link_to 'Log Out', destroy_user_session_path, 'data-turbo-method': :delete

app/views/projects/show.html.haml
- content_for :styles do
  = stylesheet_link_tag 'project'

- content_for :titlename do
  PROJECT:
  = @project.name

- content_for :center_window do
  .cleft-column
    .stats
      %h3 Project Info
      #{@project.created_at}
    - if current_user.admin?
      .destroy-button
        = link_to 'Delete PROJECT', project_path(@project),
                  data: { turbo_method: :delete,
                          turbo_confirm: 'Permanently delete this project and all of its associated resources? (not recoverable)' }
  .cright-column
    Description:
    %br
    %br
    .description-text-area
      = @project.description

- content_for :left_window do
  %h3 Deliveries
  %ul
    %li Lorem ipsum dolor sit amet, consectetur adipisicing elit.
-# - content_for :bb_a do
-#   = link_to 'New PROJECT', new_project_path

- content_for :bb_b do
  = link_to 'BACK to Main', home_path

- content_for :bb_c do
  = link_to 'EDIT Project', edit_project_path

- content_for :bb_d do
  - if user_signed_in?
    = link_to 'Log Out', destroy_user_session_path, 'data-turbo-method': :delete

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>